# -----------------------------
# 1. Збираємо React frontend
# -----------------------------
FROM node:22-alpine AS frontend-builder
WORKDIR /frontend

COPY frontend/package*.json ./

RUN npm ci

COPY frontend/ .

RUN npm run build


# -----------------------------
# 2. Запускаємо FastAPI backend
# -----------------------------
FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY --from=frontend-builder /frontend/dist /app/frontend_dist

CMD ["sh", "-c", "uvicorn app.render_app:app --host 0.0.0.0 --port ${PORT:-10000}"]